screenshot: Fix Android build error
... unused variable. Without this commit, the build will fail with the
following message:

```
make: *** [%LOCAL_APPDATA%/Android/Sdk/ndk/25.2.9519653/build/../build/core/build-binary.mk:424: obj/local/x86/objs/VkLayer_screenshot/__/__/layersvt/screenshot.o] Error 1
[x86_64] Compile++      : layer_utils <= vk_layer_config.cpp
[x86_64] Compile++      : VkLayer_screenshot <= screenshot.cpp
jni/../../layersvt/screenshot.cpp:518:10: error: variable 'pass' set but not used [-Werror,-Wunused-but-set-variable]
    bool pass;
         ^
1 error generated.
```