Fixed undefined symbols PRIu64/PRIu32 and reference to clock_gettime
Fixed undefined symbols PRIu64/PRIu32 by including <cinttypes> instead of
<inttypes.h>

Fixed undefined reference to clock_gettime by linking rt library